export type StringColourFormat =
  | 'hsl'
  | 'hsla'
  | 'namedColour'
  | 'namedTransparent'
  | 'rgbDecimal'
  | 'rgbHexLongWithHash'
  | 'rgbHexLongWithoutHash'
  | 'rgbHexShortWithHash'
  | 'rgbHexShortWithoutHash'
  | 'rgbaDecimal'
  | 'rgbaHexLongWithHash'
  | 'rgbaHexLongWithoutHash'
  | 'rgbaHexShortWithHash'
  | 'rgbaHexShortWithoutHash';
